# .streamlit/secrets.toml

[connections.gsheets]
# spreadsheet = "https://docs.google.com/spreadsheets/d/1N3E51ifcZHEHkOxT2Sq-5lAP3EmvpPwg-6_7tnR3AMk/edit?gid=1968818614#gid=1968818614"
spreadsheet = "https://docs.google.com/spreadsheets/d/1VwMQusq4jFoS0zCrluSehcn60QUJGfdsrBNFxJb5azc/edit?gid=2057527792#gid=2057527792"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
type = "service_account"  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = "sigof-sheets"
private_key_id = "2c402fd7022ef98b0f680fb167bcce71de879724"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9FFYRvo6ukKpW\ngElQu92j1e1aD4laRO++3UD5hDlus9qsXIouanhN0+Erfd3y2zuTXiPVU09bPTDC\nfyRpXn/Id2KzCCcBsVLnnxaS6t3b6hd6xCs7prsowOt12sjXnhbGRmQfrma3m5WJ\nmJf3+2HwWtPOBwbfnbPweH+tuhp1kZXnTkDuKI4DaQMBP13alLyh4Q5JzTZtwf07\nPk66pyG98iIYpAV6snvWsER1KwceBnV9Tlo+UKlRaxb1S9Im5G5E88v4bDTJsl06\n4HtNpGXAyD2+nxn0TJtMunSSfMr6j1LhX5S6xY+jZcmrYoIePJiFyvJfaBy887f3\nInA0qLyPAgMBAAECggEAPlRJ2yeaGWmO/Vzkzjxf3/ZRe/LLMHqxHZYKKTaxSBD5\n8P/AfXSTm/RQsemYFMq4ZOgPn+8KpeUSAcuv0RxZu1e/rYzubtxpm/kRk/TglfIh\nM1MffVaFM/YEqKEqvAldMJdbwiXXrocXUHiBADpaGsWWNMCUP3rZKlhOnpJOzppR\nRiZi+N0vDGQ/aid6TnotzawYGjwyR/2SVXM3goHLZyIw6ejUtDC9U4705lMFRQoN\n3lPmpIfHt7lgJCKxU+zfcQz8YMRRNGQiOx0inI4mwq+KBu8LpBvkX6pMZgwPxV3e\nGCL8uOnDKh/rm3t4v/mvqPazDPzafwW0RWrL6KCt4QKBgQD5Mc/vmx6rjykDqCcp\nmGg/5ifxX5ms8Dmri5JtAoQ/i319SdLS58yP9VKjMNJn5kWyEF5IvwNbCEdHpihf\nIQSsBH/EavI/1rUXQq0V/aIiAkqUmBq/3RbRQztto11o55md+ULF4qs5+CuEKCYs\niHjoXzhOr3EyJGHIR7Z2Y/y4rQKBgQDCPj4USKgOCsvfg9x59W39I1BjapnFEXci\nHA2/noaKTxzoihGIr14bOmCEDeLXVkkkZgtDf2pbtJRiFbSE6Jpf7JmZhQf8ttMa\n2H+jw47DJEafW2ayf8brCCMq8/Oo9you7zWieu9j/A2Z++xq36FH7+TsWmk/fQdy\nIv2dufYFqwKBgQDxzYUQ4ntzS5onwz4lHY9jGcj+bZ6n8f5z2B5AiuWa55bgQQdC\nwcx8kDccxR4V1ZshesKSYk82QSUxgCjCjj6DUGZOSNxCV+wm4vsjUJbH22NVJvcl\n37npWwzKiW/1gG5OnPVPIXC28nn/ZhoMsmxoRyVTLOhxGF6NwhBqdwFejQKBgHq7\n3XnvltCYnc1zgiJFo+PpJmhK+TJ+IKqa000am6RU7M06QG3/cRT/Q/Ds3UJ3MOwg\n1kkl/0xGw+NeF5xLZQ/rbfqFBlD2LFmwJqaRcGl5SG500GVFO6lSkPYZAwLmee8C\nEv/BcfXZU7bSacX12/Cacimtzwbgt4208k9xKzTVAoGBAPEp/6dw2dp4FJmkiF5a\nbjOKrt9Rn7rXxH0lCHPjFq3ZTT344Vgy3nLFqHfzdCcnT6t/TbOiVBA0bblWqfFo\n2CjhasX24cT3KfAdTjmV2tqArkdQzaFwehIOkskr5ciES5YkXzTCxfLkrYjaY8AM\n6QZe10s2ZqNQHSJbYwou291U\n-----END PRIVATE KEY-----\n"
client_email = "sigof-sheets-python@sigof-sheets.iam.gserviceaccount.com"
client_id = "107764238554587457185"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sigof-sheets-python%40sigof-sheets.iam.gserviceaccount.com"



[users]
sudo = "sudo"
admin = "admin"
geo = "geo"

[page_access]
sudo = ["cadastro", "editar", "relatorio", "resumos", "visualizar"]
geo = ["cadastro", "editar", "relatorio", "resumos", "visualizar"]